//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViennaRuns
{
    using System;
    using System.Collections.Generic;
    
    public partial class Run
    {
        public int r_id { get; set; }
        public string r_user { get; set; }
        public decimal r_distance { get; set; }
        public int r_duration { get; set; }
        public System.DateTime r_date { get; set; }
        public int r_datfeel { get; set; }
    
        public virtual FeelingAfterRun FeelingAfterRun { get; set; }
        public virtual User User { get; set; }
    }
}
