//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViennaRuns
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public System.DateTime w_date { get; set; }
        public string w_weather { get; set; }
        public decimal w_temperature { get; set; }
    }
}
